spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniselnew
    username: postgres
    password: prabin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      format_sql: true
    open-in-view: false

server:
  port: 8848
  servlet:
    context-path: /unisel
